name: Keep Render API Alive

on:
  workflow_dispatch:
  schedule:
    - cron: '*/14 * * * *'  # Runs every 10 minutes (adjust to */15 for every 15 min)

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the API
        run: curl -f -s -o /dev/null https://fullstack-portfolio-backend-tbnd.onrender.com/api/v1/projects/health  # Replace with your Render API URL (e.g., /health or root)
